### ISSUE TITLE
Error in early Visual Studio 2022

### ISSUE THREAD

**Issue by yeunglee** [Havunen/FormatAllFilesPlus#1]
Using this extension in Visual Studio 2022 (Version 17.1.1, not latest) got below error:

```
SetSite failed for package [FormatAllFilesPlusPackage]Source: 'FormatAllFilesPlus' Description: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=17.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=17.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.Threading, Version=17.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at FormatAllFilesPlus.FormatAllFilesPlusPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass20_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by Havunen** [comment]
Does it work for you with latest version of Visual Studio 2022?

**Comment by yeunglee** [comment]
> Does it work for you with latest version of Visual Studio 2022?

Yes. It is fine in current latest Visual Studio (e.g. Version **17.4.0**). Check the exception detail. It is pretty much about assembly version redirection.

You can reproduce this in a clean machine with early Visual Studio 2022 installation.
The early installer can be found here: https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-history

**Comment by RexChien** [comment]
I am able to successfully install the extension in VS2022 17.2.6, and I can see it in the right-click menu. However, it seems not work.
